spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: test
      password: test@2023
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
server:
  port: 8080
